type User @table {
  displayName: String!
  email: String
  createdAt: Timestamp!
}

type Category @table {
  user: User!
  name: String!
  description: String
  createdAt: Timestamp!
}

type Note @table {
  user: User!
  category: Category
  title: String!
  content: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}